module.exports = {
  'quickstart-demo.md': 'docs/tutorials/quickstart-demo.md',
  'quickstart.md': 'docs/QUICKSTART.md',
  'first-governed-agent.md': 'docs/tutorials/first-governed-agent.md',
  'add-talon-to-existing-app.md': 'docs/guides/add-talon-to-existing-app.md',
  'slack-bot-integration.md': 'docs/guides/slack-bot-integration.md',
  'openclaw-integration.md': 'docs/guides/openclaw-integration.md',
  'multi-tenant-msp.md': 'docs/guides/multi-tenant-msp.md',
  'compliance-export-runbook.md': 'docs/guides/compliance-export-runbook.md',
  'what-talon-does-to-your-request.md': 'docs/explanation/what-talon-does-to-your-request.md',
  'why-not-a-pii-proxy.md': 'docs/explanation/why-not-a-pii-proxy.md',
  'evidence-store.md': 'docs/explanation/evidence-store.md',
  'agent-planning.md': 'docs/AGENT_PLANNING.md',
  'memory-governance.md': 'docs/MEMORY_GOVERNANCE.md',
  'adoption-scenarios.md': 'docs/ADOPTION_SCENARIOS.md',
  'persona-guides.md': 'docs/PERSONA_GUIDES.md',
  'architecture-mcp-proxy.md': 'docs/ARCHITECTURE_MCP_PROXY.md',
  'configuration.md': 'docs/reference/configuration.md',
  'authentication-and-key-scopes.md': 'docs/reference/authentication-and-key-scopes.md',
  'provider-registry.md': 'docs/reference/provider-registry.md',
  'gateway-dashboard.md': 'docs/reference/gateway-dashboard.md',
  'observability.md': 'docs/OBSERVABILITY.md',
  'policy-cookbook.md': 'docs/guides/policy-cookbook.md',
  'pii-semantic-enrichment.md': 'docs/reference/pii-semantic-enrichment.md',
};
